### ISSUE TITLE
Memory usage constantly increasing by 50k/sec 80k/sec

### ISSUE THREAD

**Issue by chowdarynamala** [jdarling/MongoMQ#23]
I am facing one problem with using this module in my node js implementation. I just created an object of MongoMQ as follows.

var queue = new MongoMQ({
  autoStart: true,
  databaseName: <dbName>, 
  queueCollection: <collectioName>,
  connectionString: <my db connection string>
});

After this I started my node, and I can see the memory used by node keep on increasing. Can anyone please help me on this? If I comment the above code, then memory not increasing.

Thanks
Lakshmi Narayana

**Comment by teomurgi** [comment]
Any update on this?

**Comment by jdarling** [comment]
I think this has something to do with Windows and Garbage collection as I can't duplicate it on my Linux machines.  I see a ramp up of memory but after time it levels off and stays constant.

I'll be upgrading to the latest node-mongo-native driver soon for this project and rewriting a bunch of core code that by today's standards is quite sloppy.

I know everyone hates the "I don't use Windows" excuse, but its the truth.  Hopefully the rewrite catches whatever is causing the issue.

**Comment by chowdarynamala** [comment]
Hi,

Is there any update on this issue? I just started the Queue and left like that without doing any opeations. But still I see memory increase. Can you please help me on this? Again, I am using this on Windows only.
Thanks

**Comment by chowdarynamala** [comment]
Also the same issue is observed when executing the examples 'basic' by using 'node talker.js' only. Memory increasing by 4k/sec.
